sudo: required
language: generic

services:
    - docker

before_install:
    - docker build -t aschmitt/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true aschmitt/react-test npm run test

after_success:
    - docker build -t aschmitt/multi-client ./client
    - docker build -t aschmitt/multi-nginx ./nginx
    - docker build -t aschmitt/multi-server ./server
    - docker build -t aschmitt/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push aschmitt/multi-client
    - docker push aschmitt/multi-nginx
    - docker push aschmitt/multi-server
    - docker push aschmitt/multi-worker

deploy:
    provider: elasticbeanstalk
    region: "eu-central-1"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "multi-docker-bucket"
    bucket_path: "multi-docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY